version: '3.8'
services:
  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - zookeeper
      - kafka
      - mysql

  nginx:
    image: nginx:alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  zookeeper:
    image: zookeeper:3.8
    container_name: lab7_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: lab7_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "lab7_orders:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    container_name: lab7_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab7_db
      MYSQL_USER: lab7_user
      MYSQL_PASSWORD: lab7_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: